# Generated by Django 4.2.16 on 2024-11-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=100)),
                ('no_control', models.CharField(max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('url_imagen', models.URLField(blank=True, max_length=512, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('lugar_encontrado', models.CharField(max_length=100)),
                ('entregado', models.BooleanField(default=False)),
                ('solicitado', models.BooleanField(default=False)),
                ('usuario_objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
